### ISSUE TITLE
issue with the formula

### ISSUE THREAD

**Issue by levi3001** [qbeer/coco-froc-analysis#13]
for the use_IOU function, I dont understand why you need to get the uniform distribution as in the formula, and I also believe that you use wrong () 
![image](https://github.com/qbeer/coco-froc-analysis/assets/61280804/30306842-0b69-45cc-ab7a-fc192398b89a)

also I think when you use linear sum assignment function, row_ind = len(gt) which is not our desired

**Comment by qbeer** [comment]
I do not think that you are right, we recently heavily tested the code against many other solutions and added documentation also.
