### ISSUE TITLE
use_iou=True not working?

### ISSUE THREAD

**Issue by wolfryu** [qbeer/coco-froc-analysis#7]
Thank you for your work and share!
I have a test json from coco dataset.
when I set use_iou=True, and play with iou_thres, I get the same FROC picture everytime.
It looks like use_iou=True is not working.

here is the gt and predict json file I am using.
https://drive.google.com/file/d/1Z8E3kmQ_BYIoZoPLX4xbFOp3Rd2h7wb4/view?usp=sharing
https://drive.google.com/file/d/1eoqKkpKSYxUd4NCWy-WkEbCKYbaQdIGa/view?usp=sharing

and the code I am running this is:

```
from froc_analysis import generate_froc_curve
generate_froc_curve(gt_ann='/data/testcoco100_c0_gt.json',
                    pr_ann='/data/testcoco100_c0_pd.json',
                    use_iou=True, iou_thres=0.8, n_sample_points=75,
                    plot_title='FROC', plot_output_path='dummy08.png')

generate_froc_curve(gt_ann='/data/testcoco100_c0_gt.json',
                    pr_ann='/data/testcoco100_c0_pd.json',
                    use_iou=True, iou_thres=0.000001, n_sample_points=75,
                    plot_title='FROC', plot_output_path='dummy0000001.png')
```

Could you take a look on this issue? 
Thank you so much!

**Comment by shivasv97** [comment]
Yes, I too have this same issue. 
Do you have the source which has the algorithm defined for FROC calculation using IoU as the threshold? Could you please link to it?

**Comment by qbeer** [comment]
This is fixed now.
