### ISSUE TITLE
Updates are required in the usage

### ISSUE THREAD

**Issue by wangyunpengbio** [qbeer/coco-froc-analysis#9]
Your repository is handy, thank you for your contribution!
I find the usage in the [README.md](https://github.com/qbeer/coco-froc-analysis/blob/master/README.md) needs to be updated 
I install your package by `python setup.py install`. When using the following code shown in the usage,
`from froc_analysis import generate_froc_curve, generate_bootstrap_curves`
It turns out to be `ImportError cannot import name 'generate_bootstrap_curves'`. I think this is because the code has been upgraded and the usage has not been updated. I found the new function `generate_bootstrap_froc_curves` can be imported and it seems to have the same function as the `'generate_bootstrap_curves'`. 
I am interested in the **new function `count_curve`**, is this used to plot the Precision-Recall Curve ([PR curve](https://www.geeksforgeeks.org/precision-recall-curve-ml/))? I would be grateful if you could give me some information about it. I am looking forward to your reply.

**Comment by qbeer** [comment]
Hi, the `count_curve` calculates a precision-recall curve based on the density. It also takes `test.json`s from annotators and puts their specific precsion-recall point to the image. It works the exact same way as the FROC generation. Please check the updated README and if it works fine for you too I'll close this issue.

Very sorry for the late answer.
